language: cpp
compiler:
  - g++
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - mkdir test/build && cd test/build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCOLLECT_COVERAGE=On ..
  - make
script:
  - ./loquat-test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-4.8
      - cmake
      - cmake-data
sudo: false
